---
title: "Cut sp by bbox"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Cut sp by bbox}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

Cut a `SpatialPolygonsDataFrame` by a `bbox`. First lets load the data and choose a county.

```{r, fig.height = 7, fig.width = 7}
library(histmaps)
library(sp)

svelan <- hist_boundaries(1900, "county")
jkpg = 6
sub_sl <- subset(svelan, lan == jkpg)
plot(svelan)
plot(sub_sl, col = "red", add = T)
```

The county

```{r, fig.height = 7, fig.width = 7}
plot(sub_sl)
```

Add a the boundary box.

```{r, fig.height = 7, fig.width = 7}
bb <- bbox(sub_sl)
bb[ ,1] <- bb[ ,1] - 5000
bb[ ,2] <- bb[ ,2] + 5000
b_poly <- as(raster::extent(as.vector(t(bb))), "SpatialPolygons")
plot(b_poly, border = "red")
plot(sub_sl, add = T)
```

Cut county map by a county boundary box.

```{r, fig.height = 7, fig.width = 7}
cut_county <- clip_spdf(svelan, bb)
plot(cut_county)
plot(sub_sl, lwd = 2, border = "red", add = T)
```

Subset parishes by county and cut county by boundary box using the wrapper function `cut_spbox`.

```{r, fig.height = 7, fig.width = 7}
parish <- hist_boundaries(1900, "parish")
par_sub <- subset(parish, county == jkpg)

base_map <- cut_spbox(svelan, sub_sl, 5000)
plot(base_map, col = "#DEDEC8")
plot(sub_sl, lwd = 2, add = T)
plot(par_sub, col = "#F5F5DC", add = T)
```

Or in ggplot

```{r ggplot, fig.height = 7, fig.width = 7}
library(maptools)
library(ggplot2)
library(dplyr)

g_base <- sp_to_ggplot(base_map)
g_jkpg <- sp_to_ggplot(sub_sl)
g_pars <- sp_to_ggplot(par_sub)
g_town <- hist_boundaries(1900, "town", "df") %>% 
  filter(code == jkpg)

ggplot() +
  geom_polygon(
    data = g_base, aes(long, lat, group = group), fill = "#DEDEC8", color = "#FFFFFF") + 
  geom_polygon(
    data = g_pars, aes(long, lat, group = group), fill = "#E6E6B3", color = "#FFFFFF") +
  geom_path(data = g_jkpg, aes(long, lat, group = group), size = 1, color = "#FFFFFF") +
  geom_point(data = g_town, aes(lon, lat), size = 3, color = "black") +
  geom_text(data = g_town, aes(lon, lat, label = town, hjust = -0.1)) + 
  coord_equal() + theme_minimal() + 
  theme(
    axis.text  = element_blank(), 
    axis.ticks = element_blank(), 
    axis.title = element_blank())
```